#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""gen-whats-new.py — the release-highlights page of the website, from CHANGELOG.md.

The website had no answer to "what changed?". Every release note lived in CHANGELOG.md —
221 KB of it, on GitHub, two clicks away and written newest-first in one unbroken column —
so a visitor who wanted to know what the last few months added either read the whole thing
or did not find out. The homepage said what the app *is*, the version-notes page said what
the preview *cannot* do, and nothing said what had just happened.

This generates that page, and generates it rather than asking somebody to write it twice:
each release in CHANGELOG.md already opens with a paragraph or three of prose that says what
the release was *about*, and every entry below that opens with a bold sentence that is
already a headline. Those are the two things a highlights page is made of. Re-typing them
into a second file would only create a second file to forget.

Outputs (regenerable, never hand-edited):
  docs/content/user-guide/whats-new.md   — one section per release, newest first
  docs/content/website/index.md          — the band between the BAND markers (latest release)

Fails loudly rather than shipping something wrong:
  • a release whose heading it cannot parse
  • prose carrying a term docs/metadata/terminology.yml forbids (check-docs.py would fail on
    the generated page, which is the wrong place to find out — the fix belongs in the CHANGELOG)
  • a relative Markdown link in the prose, which resolves inside the repository but not on a
    site whose pages are staged flat
  • the homepage losing its markers

Usage: python3 docs/scripts/gen-whats-new.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("need pyyaml: python3 -m pip install --user pyyaml")

REPO = Path(__file__).resolve().parents[2]
CHANGELOG = REPO / "CHANGELOG.md"
TERMS_YML = REPO / "docs/metadata/terminology.yml"
PAGE = REPO / "docs/content/user-guide/whats-new.md"
HOMEPAGE = REPO / "docs/content/website/index.md"
REPO_URL = "https://github.com/hkiam/PeachCommander"

BAND_BEGIN = "<!-- BEGIN latest-release (generated by docs/scripts/gen-whats-new.py) -->"
BAND_END = "<!-- END latest-release -->"

# Releases keep coming; the page must not grow without bound, and it tapers rather than
# stopping dead: the newest two are what a visitor came for and list everything they added, the
# four below that give a taste, and older ones are carried by their own prose — with the full
# notes always one link away.
FULL_HIGHLIGHTS = 2      # releases that list every headline
BRIEF_UNTIL = 6          # releases that list a few
BRIEF_HIGHLIGHTS = 4     # how many "a few" is

# Where a headline list comes from: what the release gained, then what it closed, then what it
# changed. "Fixed" last because a release that only fixed things is described better by its
# count than by four sentences out of forty-six.
HIGHLIGHT_SECTIONS = ["Added", "Security", "Changed", "Fixed"]

# The counts that become chips, in reading order. A release may invent a section of its own
# ("Documentation", "Internal", "Plugins"); those still count towards the total behind the
# "in full" link, but they are not what somebody scanning a release wants first.
COUNT_ORDER = ["Added", "Changed", "Fixed", "Security"]
COUNT_LABEL = {"Added": "new", "Changed": "changed", "Fixed": "fixed", "Security": "security"}

# Prose the page deliberately drops. Every release up to 0.6.x repeated the signing warning in
# its own opening, which was right in a file read one release at a time and is noise on a page
# that shows nineteen of them — the installation page and the download section each say it once.
PROSE_SKIP = ("**Still unsigned",)

# A headline derived from a bullet that has no bold opening (the oldest releases wrote plain
# ones) is cut here, at the last natural break before the limit rather than mid-word.
HEADLINE_MAX = 120
HEADLINE_BREAKS = (": ", " — ", ", ")

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

HEAD_RE = re.compile(r"^## \[(?P<version>[^\]]+)\](?:\s*[—–-]\s*(?P<date>\d{4}-\d{2}-\d{2}))?\s*$")
LINKDEF_RE = re.compile(r"^\[[^\]]+\]:\s+\S+")
FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`[^`]*`")
LINK_RE = re.compile(r"(?<!\!)\[[^\]]*\]\(([^)]+)\)")
# The bold sentence a CHANGELOG entry opens with. Non-greedy, over the bullet joined back into
# one line — plenty of them wrap, and a regex run per physical line finds an unterminated `**`
# and gives up.
LEAD_IN_RE = re.compile(r"^\*\*(.+?)\*\*", re.DOTALL)


def headline(bullet: str) -> str:
    """The one-line headline of a CHANGELOG entry.

    Entries have opened with a bold sentence since 0.3.0 and that sentence *is* the headline.
    The oldest releases wrote plain bullets, so those are cut down to their first sentence —
    which is why 0.2.0 is not a card with nothing in it.
    """
    m = LEAD_IN_RE.match(bullet)
    if m:
        return " ".join(m.group(1).split())
    text = " ".join(bullet.split())
    sentence = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]
    if len(sentence) <= HEADLINE_MAX:
        return sentence
    for brk in HEADLINE_BREAKS:
        cut = sentence.rfind(brk, 0, HEADLINE_MAX)
        if cut > HEADLINE_MAX // 2:
            return sentence[:cut]
    return sentence[:HEADLINE_MAX].rsplit(" ", 1)[0] + "…"


def as_sentence(text: str) -> str:
    """A headline reads as one line of a list, so it ends like one."""
    text = text.rstrip(":")
    return text if text.endswith((".", "!", "?", "…")) else text + "."


class Release:
    def __init__(self, version: str, date: str | None):
        self.version = version
        self.date = date
        self.prose = ""
        self.sections: dict[str, list[str]] = {}

    @property
    def tag(self) -> str:
        return f"v{self.version}"

    @property
    def total(self) -> int:
        return sum(len(v) for v in self.sections.values())

    def headlines(self) -> tuple[str, list[str]]:
        """(section name, headlines) from the first section of that release that has entries."""
        for name in HIGHLIGHT_SECTIONS + sorted(self.sections):
            bullets = self.sections.get(name) or []
            if bullets:
                return name, [as_sentence(headline(b)) for b in bullets]
        return "", []

    def counts(self) -> list[str]:
        """The chips: how much of each kind, the four kinds a reader recognises.

        A release that split one of them ("Fixed — data", "Fixed — things that were quietly
        wrong") is still reporting fixes, and two chips reading "8 fixed — data" and "12 fixed —
        things that were quietly wrong" say less than one reading "20 fixed".
        """
        tally: dict[str, int] = {}
        for name, bullets in self.sections.items():
            kind = name.split("—")[0].split("–")[0].strip()
            if kind in COUNT_ORDER:
                tally[kind] = tally.get(kind, 0) + len(bullets)
        return [f"{tally[k]} {COUNT_LABEL[k]}" for k in COUNT_ORDER if tally.get(k)]


def human_date(iso: str | None) -> str:
    if not iso:
        return ""
    y, m, d = (int(p) for p in iso.split("-"))
    return f"{d} {MONTHS[m - 1]} {y}"


def parse_changelog() -> list[Release]:
    """Every released version in CHANGELOG.md, newest first.

    `[Unreleased]` is skipped: it is a working note, and a website section headed "Unreleased"
    would promise something nobody can download.
    """
    releases: list[Release] = []
    current: Release | None = None
    section: str | None = None
    bullet: list[str] | None = None

    def flush_bullet():
        nonlocal bullet
        if bullet is not None and current is not None and section is not None:
            current.sections.setdefault(section, []).append("\n".join(bullet).strip())
        bullet = None

    for raw in CHANGELOG.read_text(encoding="utf-8").split("\n"):
        if raw.startswith("## "):
            flush_bullet()
            m = HEAD_RE.match(raw)
            if not m:
                sys.exit(f"gen-whats-new.py: cannot read release heading {raw!r} — expected "
                         f"'## [x.y.z] — YYYY-MM-DD'")
            section = None
            if m.group("version").lower() == "unreleased":
                current = None
                continue
            current = Release(m.group("version"), m.group("date"))
            releases.append(current)
            continue
        if current is None:
            continue
        if raw.startswith("### "):
            flush_bullet()
            section = raw[4:].strip()
            current.sections.setdefault(section, [])
            continue
        if section is None:
            # Still in the release's own prose. The link definitions at the foot of the file sit
            # under the oldest release and are not part of it.
            if not LINKDEF_RE.match(raw):
                current.prose += raw + "\n"
            continue
        if raw.startswith("- "):
            flush_bullet()
            bullet = [raw[2:]]
        elif bullet is not None and raw.strip():
            bullet.append(raw.strip())        # a wrapped bullet, joined back into one line
        elif bullet is not None:
            flush_bullet()
    flush_bullet()

    for r in releases:
        paragraphs = [p for p in r.prose.strip().split("\n\n")
                      if p.strip() and not p.lstrip().startswith(PROSE_SKIP)]
        r.prose = "\n\n".join(p.strip("\n") for p in paragraphs)
    return releases


def check_prose(where: str, text: str, avoid: dict[str, str]) -> list[str]:
    """Terminology and link problems in text that is about to become a documentation page."""
    problems = []
    clean = INLINE_CODE_RE.sub(" ", FENCE_RE.sub(" ", text))
    low = clean.lower()
    for bad, good in avoid.items():
        if re.search(rf"\b{re.escape(bad)}\b", low):
            problems.append(f"{where}: forbidden term '{bad}' (use '{good}') — fix it in CHANGELOG.md")
    for url in LINK_RE.findall(clean):
        if not url.startswith(("http://", "https://", "#", "mailto:")):
            problems.append(f"{where}: relative link '{url}' — the site stages pages flat, so "
                            f"write an absolute {REPO_URL}/… link in CHANGELOG.md")
    return problems


def forbidden_terms() -> dict[str, str]:
    terms = yaml.safe_load(TERMS_YML.read_text(encoding="utf-8"))["terms"]
    return {bad.lower(): t["term"] for t in terms for bad in (t.get("avoid") or [])}


def render_page(releases: list[Release]) -> str:
    latest = releases[0]
    lines = [
        "---",
        "title: What's new",
        "slug: whats-new",
        "group: Get started",
        "section: user-guide",
        "order: 80",
        "related: [version-notes, known-limitations, installation]",
        "---",
        "",
        "<!-- Generated from CHANGELOG.md by docs/scripts/gen-whats-new.py. Do not edit by hand. -->",
        "",
        "# What's new",
        "",
        f"Peach Commander is at **{latest.version}**, released {human_date(latest.date)}. "
        "Every release is written up in full in the "
        f"[changelog]({REPO_URL}/blob/main/CHANGELOG.md) — this page is the shorter read: what "
        "each one was about, newest first, and what it added.",
        "",
    ]

    for index, r in enumerate(releases):
        classes = "pc-release pc-release--latest" if index == 0 else "pc-release"
        date = human_date(r.date)
        lines += [f'<div class="{classes}" markdown="1">', ""]
        lines.append(f'## {r.version} <span class="pc-release__date">{date}</span>'
                     if date else f"## {r.version}")
        lines.append("")

        chips = [f'<span class="pc-chip pc-chip--now">Latest release</span>'] if index == 0 else []
        chips += [f'<span class="pc-chip">{c}</span>' for c in r.counts()]
        if chips:
            lines += [f'<p class="pc-release__chips">{"".join(chips)}</p>', ""]

        if r.prose:
            lines += [r.prose, ""]

        name, heads = r.headlines()
        if index < FULL_HIGHLIGHTS:
            shown = heads
            label = "What it added" if name == "Added" else "Highlights"
        elif index < BRIEF_UNTIL or not r.prose:
            # Below the top two a few headlines are a taste rather than a list — except where a
            # release wrote no prose at all, which is the only thing standing between that
            # release and a card with nothing in it.
            shown = heads[:BRIEF_HIGHLIGHTS]
            label = "Highlights"
        else:
            shown = []
        if shown:
            lines += [f"**{label}**", ""]
            lines += [f"- {h}" for h in shown]
            lines.append("")

        rest = r.total - len(shown)
        note = "note" if rest == 1 else "notes"
        if not r.total:
            more = "the release on GitHub"
        elif rest == r.total:
            more = f"all {r.total} {note}"
        elif rest:
            more = f"the other {rest} {note}"
        else:
            more = "the release itself"
        lines += [f'<p class="pc-release__more">'
                  f'<a href="{REPO_URL}/releases/tag/{r.tag}">{r.version} in full — {more} &rarr;</a></p>',
                  "", "</div>", ""]

    lines += [
        "## The whole story",
        "",
        f"Every release ever made is listed on the [releases page]({REPO_URL}/releases), and the "
        f"complete history — including the notes that are too detailed for this page — is in "
        f"[CHANGELOG.md]({REPO_URL}/blob/main/CHANGELOG.md).",
        "",
        "Peach Commander is still before 1.0, so behaviour it got wrong may still change between "
        "releases. [Version notes](version-notes.md) says what the current preview can and cannot "
        "do, and [Known limitations](known-limitations.md) has the honest list.",
        "",
    ]
    return "\n".join(lines)


def render_band(latest: Release) -> str:
    """The homepage band: what the newest release was about, in its own first sentence."""
    first = (latest.prose.split("\n\n")[0] if latest.prose else "").replace("\n", " ").strip()
    lead = f'<p class="pc-whatsnew__lead">{first}</p>' if first else ""
    return "\n".join([
        BAND_BEGIN,
        '<div class="pc-whatsnew" markdown="1">',
        f'<p class="pc-whatsnew__eyebrow">New in {latest.version} · {human_date(latest.date)}</p>',
        lead,
        '<p class="pc-whatsnew__go"><a href="whats-new.html">What changed in every release '
        "&rarr;</a></p>",
        "</div>",
        BAND_END,
    ])


def replace_band(text: str, band: str) -> str:
    start, end = text.find(BAND_BEGIN), text.find(BAND_END)
    if start < 0 or end < 0:
        sys.exit(f"gen-whats-new.py: {HOMEPAGE.relative_to(REPO)} has no "
                 f"{BAND_BEGIN} / {BAND_END} markers — this generator keeps the band between "
                 f"them up to date and will not guess where it belongs")
    return text[:start] + band + text[end + len(BAND_END):]


def main() -> int:
    releases = parse_changelog()
    if not releases:
        sys.exit("gen-whats-new.py: no released version found in CHANGELOG.md")

    avoid = forbidden_terms()
    problems = []
    for r in releases:
        problems += check_prose(f"{r.version} prose", r.prose, avoid)
        for head in r.headlines()[1]:
            problems += check_prose(f"{r.version} headline", head, avoid)
    if problems:
        for p in problems:
            print("  ❌", p, file=sys.stderr)
        sys.exit("gen-whats-new.py: the CHANGELOG prose this page is built from would fail the "
                 "documentation gate")

    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(render_page(releases), encoding="utf-8")
    HOMEPAGE.write_text(
        replace_band(HOMEPAGE.read_text(encoding="utf-8"), render_band(releases[0])),
        encoding="utf-8")

    print(f"✓ whats-new.md ({len(releases)} releases, newest {releases[0].version})")
    print(f"✓ index.md (latest-release band → {releases[0].version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
