// SPDX-License-Identifier: Apache-2.0
import XCTest
@testable import PCFoundation

final class ChecksumFileTests: XCTestCase {

    func testFormatForAlgorithm() {
        XCTAssertEqual(ChecksumFileFormat.for(.crc32), .sfv)
        XCTAssertEqual(ChecksumFileFormat.for(.md5), .digestFirst)
        XCTAssertEqual(ChecksumFileFormat.for(.sha256), .digestFirst)
    }

    func testParseSFV() {
        let text = "; generated by something\ntest.txt CBF43926\nmy file.txt 12345678\n"
        let entries = ChecksumFile.parse(text, format: .sfv)
        XCTAssertEqual(entries, [
            ChecksumEntry(digest: "cbf43926", filename: "test.txt"),
            ChecksumEntry(digest: "12345678", filename: "my file.txt")   // filename with space
        ])
    }

    func testParseDigestFirst() {
        let text = """
        900150983cd24fb0d6963f7d28e17f72  file.bin
        d41d8cd98f00b204e9800998ecf8427e *binary mode.dat
        # a comment

        """
        let entries = ChecksumFile.parse(text, format: .digestFirst)
        XCTAssertEqual(entries, [
            ChecksumEntry(digest: "900150983cd24fb0d6963f7d28e17f72", filename: "file.bin"),
            ChecksumEntry(digest: "d41d8cd98f00b204e9800998ecf8427e", filename: "binary mode.dat")
        ])
    }

    func testGenerateSFVUppercasesDigest() {
        let out = ChecksumFile.generate([ChecksumEntry(digest: "cbf43926", filename: "a.txt")], format: .sfv)
        XCTAssertEqual(out, "a.txt CBF43926\n")
    }

    func testGenerateDigestFirst() {
        let out = ChecksumFile.generate([ChecksumEntry(digest: "ABCDEF", filename: "a.bin")], format: .digestFirst)
        XCTAssertEqual(out, "abcdef  a.bin\n")   // digest normalized to lowercase
    }

    func testRoundTrip() {
        let entries = [
            ChecksumEntry(digest: "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", filename: "doc.pdf"),
            ChecksumEntry(digest: "0123456789abcdef0123456789abcdef01234567", filename: "some file.tar")
        ]
        for format in [ChecksumFileFormat.sfv, .digestFirst] {
            let round = ChecksumFile.parse(ChecksumFile.generate(entries, format: format), format: format)
            XCTAssertEqual(round, entries, "round-trip failed for \(format)")
        }
    }
}
