// SPDX-License-Identifier: Apache-2.0
import XCTest
@testable import PCFoundation

final class ChecksumFileTests: XCTestCase {

    // MARK: - How these files actually arrive (F-097)
    //
    // Every test below this line existed only as an LF variant, which is why the defect they now pin
    // survived: `parse` split on `$0 == "\n"`, and in Swift a CRLF is a *single* Character, so it is not
    // equal to a line feed. A Windows-written .sfv — which is nearly all of them, the format comes from
    // Windows tools — therefore parsed as one enormous line and verified nothing at all.

    func testACRLFSFVFileParses() {
        let text = "; generated by WIN-SFV32\r\ntest.txt CBF43926\r\nmy file.txt 12345678\r\n"
        XCTAssertEqual(ChecksumFile.parse(text, format: .sfv), [
            ChecksumEntry(digest: "cbf43926", filename: "test.txt"),
            ChecksumEntry(digest: "12345678", filename: "my file.txt")
        ])
    }

    func testACRLFDigestFileParses() {
        // The md5 case failed differently and worse: one entry survived, with the rest of the file
        // hanging off its filename — so the check ran against a name that cannot exist and reported the
        // user's intact files as missing.
        let text = "900150983cd24fb0d6963f7d28e17f72  file.bin\r\nd41d8cd98f00b204e9800998ecf8427e  b.bin\r\n"
        XCTAssertEqual(ChecksumFile.parse(text, format: .digestFirst), [
            ChecksumEntry(digest: "900150983cd24fb0d6963f7d28e17f72", filename: "file.bin"),
            ChecksumEntry(digest: "d41d8cd98f00b204e9800998ecf8427e", filename: "b.bin")
        ])
    }

    func testALoneCarriageReturnIsAlsoALineBreak() {
        // Classic-Mac line endings still turn up beside old archives; before, both lines ran together
        // into a single entry with a nonsense filename.
        let text = "a.txt 12345678\rb.txt 9abcdef0\r"
        XCTAssertEqual(ChecksumFile.parse(text, format: .sfv), [
            ChecksumEntry(digest: "12345678", filename: "a.txt"),
            ChecksumEntry(digest: "9abcdef0", filename: "b.txt")
        ])
    }

    func testAByteOrderMarkDoesNotSwallowTheFirstLine() {
        // A BOM made the first digest fail the hex test, so the first file in the list was silently
        // never checked — the quietest way for a verification feature to be wrong.
        let bom = "\u{FEFF}"
        XCTAssertEqual(ChecksumFile.parse(bom + "900150983cd24fb0d6963f7d28e17f72  file.bin\n",
                                          format: .digestFirst),
                       [ChecksumEntry(digest: "900150983cd24fb0d6963f7d28e17f72", filename: "file.bin")])
        XCTAssertEqual(ChecksumFile.parse(bom + "a.txt 12345678\r\n", format: .sfv),
                       [ChecksumEntry(digest: "12345678", filename: "a.txt")])
    }

    func testMixedLineEndingsInOneFile() {
        // Files edited on two systems exist; neither half may be lost.
        let text = "a.txt 11111111\r\nb.txt 22222222\nc.txt 33333333\r\n"
        XCTAssertEqual(ChecksumFile.parse(text, format: .sfv).map(\.filename),
                       ["a.txt", "b.txt", "c.txt"])
    }

    func testFormatForAlgorithm() {
        XCTAssertEqual(ChecksumFileFormat.for(.crc32), .sfv)
        XCTAssertEqual(ChecksumFileFormat.for(.md5), .digestFirst)
        XCTAssertEqual(ChecksumFileFormat.for(.sha256), .digestFirst)
    }

    func testParseSFV() {
        let text = "; generated by something\ntest.txt CBF43926\nmy file.txt 12345678\n"
        let entries = ChecksumFile.parse(text, format: .sfv)
        XCTAssertEqual(entries, [
            ChecksumEntry(digest: "cbf43926", filename: "test.txt"),
            ChecksumEntry(digest: "12345678", filename: "my file.txt")   // filename with space
        ])
    }

    func testParseDigestFirst() {
        let text = """
        900150983cd24fb0d6963f7d28e17f72  file.bin
        d41d8cd98f00b204e9800998ecf8427e *binary mode.dat
        # a comment

        """
        let entries = ChecksumFile.parse(text, format: .digestFirst)
        XCTAssertEqual(entries, [
            ChecksumEntry(digest: "900150983cd24fb0d6963f7d28e17f72", filename: "file.bin"),
            ChecksumEntry(digest: "d41d8cd98f00b204e9800998ecf8427e", filename: "binary mode.dat")
        ])
    }

    func testGenerateSFVUppercasesDigest() {
        let out = ChecksumFile.generate([ChecksumEntry(digest: "cbf43926", filename: "a.txt")], format: .sfv)
        XCTAssertEqual(out, "a.txt CBF43926\n")
    }

    func testGenerateDigestFirst() {
        let out = ChecksumFile.generate([ChecksumEntry(digest: "ABCDEF", filename: "a.bin")], format: .digestFirst)
        XCTAssertEqual(out, "abcdef  a.bin\n")   // digest normalized to lowercase
    }

    func testRoundTrip() {
        let entries = [
            ChecksumEntry(digest: "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", filename: "doc.pdf"),
            ChecksumEntry(digest: "0123456789abcdef0123456789abcdef01234567", filename: "some file.tar")
        ]
        for format in [ChecksumFileFormat.sfv, .digestFirst] {
            let round = ChecksumFile.parse(ChecksumFile.generate(entries, format: format), format: format)
            XCTAssertEqual(round, entries, "round-trip failed for \(format)")
        }
    }
}
