#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""apply-plugin-translations.py — write plugin .lproj files from translation dictionaries.

The app's strings live in one String Catalog and have `Tools/apply-translations.py`. A plugin's
strings live in its own bundle (see `Plugins/SDK/PluginLoc.swift`), one `Localizable.strings` per
language, so they need the same treatment one level down: a dictionary per plugin per language,
applied mechanically.

    Tools/plugin-translations/<Plugin>/<lang>.json    { english_key: translated_value }
        ->  Plugins/<Plugin>/Resources/<lang>.lproj/Localizable.strings

English is never written from a dictionary: `en.lproj` is the source and stays hand-maintained, since
its keys ARE the English text. A key in a dictionary that no longer exists in `en.lproj` is reported
as stale rather than written, because it would sit in the bundle answering a question nobody asks.

Idempotent. Usage: Tools/apply-plugin-translations.py [plugin ...]   (default: all)
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANS_DIR = os.path.join(ROOT, "Tools/plugin-translations")
PLUGINS = os.path.join(ROOT, "Plugins")

KEY_RE = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=', re.M)


def english_keys(plugin):
    """The keys of a plugin's source language, in file order — which is the order we write."""
    path = os.path.join(PLUGINS, plugin, "Resources/en.lproj/Localizable.strings")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as handle:
        return KEY_RE.findall(handle.read())


def escape(value):
    """Escape for a .strings value: backslashes first, then quotes, then real newlines."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def apply(plugin, lang, keys):
    path = os.path.join(TRANS_DIR, plugin, f"{lang}.json")
    with open(path, encoding="utf-8") as handle:
        translations = json.load(handle)

    stale = [k for k in translations if k not in keys]
    for key in stale:
        print(f"  [stale] {plugin}/{lang}: {key!r} is not in en.lproj")

    lines = [f"/* {plugin} plugin — {lang}. Generated by Tools/apply-plugin-translations.py. */"]
    written = 0
    for key in keys:
        value = translations.get(key)
        if not value:
            continue          # left out entirely: `L` falls back to the English key
        lines.append(f'"{escape(key)}" = "{escape(value)}";')
        written += 1

    out_dir = os.path.join(PLUGINS, plugin, "Resources", f"{lang}.lproj")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "Localizable.strings"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return written, len(stale)


def main():
    wanted = sys.argv[1:]
    plugins = sorted(d for d in os.listdir(TRANS_DIR)
                     if os.path.isdir(os.path.join(TRANS_DIR, d)))
    if wanted:
        plugins = [p for p in plugins if p in wanted]

    for plugin in plugins:
        keys = english_keys(plugin)
        if keys is None:
            print(f"!! {plugin}: no en.lproj to translate against", file=sys.stderr)
            continue
        langs = sorted(f[:-5] for f in os.listdir(os.path.join(TRANS_DIR, plugin))
                       if f.endswith(".json") and f != "en.json")
        for lang in langs:
            written, stale = apply(plugin, lang, keys)
            print(f"==> {plugin}/{lang}: {written}/{len(keys)} translated"
                  f"{f' ({stale} stale)' if stale else ''}")


if __name__ == "__main__":
    main()
