// OpenSourceWindowController.swift - "Open Source & Third-Party Software" window.
//
// A searchable list of every bundled open-source component (name / version /
// license / website) with a detail pane showing the description, copyright,
// repository link and full license text. Data is read entirely from the bundled
// Resources/ThirdPartyNotices.json (generated by Tools/generate-third-party-notices.py)
// and the per-component texts in Resources/Licenses/, so the dialog stays in sync
// with the actual dependencies without any hand-maintained UI.

import AppKit

// MARK: - Model (mirrors ThirdPartyNotices.json)

struct ThirdPartyComponent: Codable {
    let name: String
    let version: String
    let license: String
    let copyright: String
    let description: String
    let website: String
    let repository: String
    let licenseFile: String
    let note: String
}

struct ThirdPartyExternalTool: Codable {
    let name: String
    let license: String
    let url: String
    let note: String
}

struct ThirdPartyNotices: Codable {
    let components: [ThirdPartyComponent]
    let externalTools: [ThirdPartyExternalTool]
    let acknowledgement: String

    static func load() -> ThirdPartyNotices? {
        guard let url = Bundle.main.url(forResource: "ThirdPartyNotices", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let notices = try? JSONDecoder().decode(ThirdPartyNotices.self, from: data) else { return nil }
        return notices
    }
}

final class OpenSourceWindowController: NSWindowController, NSTableViewDataSource, NSTableViewDelegate {
    private let notices: ThirdPartyNotices
    private var filtered: [ThirdPartyComponent]

    private let search = NSSearchField()
    private let table = NSTableView()
    private let detail = NSTextView()
    private let websiteButton = NSButton()
    private let repoButton = NSButton()

    /// Returns nil when the bundled notices file is missing/unreadable.
    static func make() -> OpenSourceWindowController? {
        ThirdPartyNotices.load().map { OpenSourceWindowController(notices: $0) }
    }

    init(notices: ThirdPartyNotices) {
        self.notices = notices
        self.filtered = notices.components
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 860, height: 580),
                              styleMask: [.titled, .closable, .resizable, .miniaturizable],
                              backing: .buffered, defer: false)
        window.title = String(localized: "Open Source & Third-Party Software")
        super.init(window: window)
        buildUI()
        if !filtered.isEmpty {
            table.selectRowIndexes([0], byExtendingSelection: false)
            showDetail(filtered[0])
        }
    }
    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    func present() { window?.center(); showWindow(nil); window?.makeKeyAndOrderFront(nil) }

    // MARK: - UI

    private func buildUI() {
        guard let content = window?.contentView else { return }

        search.placeholderString = String(localized: "Filter libraries")
        search.target = self
        search.action = #selector(filterChanged)
        search.sendsSearchStringImmediately = true

        for (id, title, width) in [("name", String(localized: "Library"), CGFloat(200)),
                                   ("version", String(localized: "Version"), 130),
                                   ("license", String(localized: "License"), 120),
                                   ("website", String(localized: "Website"), 260)] {
            let col = NSTableColumn(identifier: .init(id)); col.title = title; col.width = width
            table.addTableColumn(col)
        }
        table.usesAlternatingRowBackgroundColors = true
        table.dataSource = self
        table.delegate = self
        table.rowSizeStyle = .default
        table.allowsColumnResizing = true
        let tableScroll = NSScrollView()
        tableScroll.documentView = table
        tableScroll.hasVerticalScroller = true
        tableScroll.borderType = .bezelBorder
        tableScroll.translatesAutoresizingMaskIntoConstraints = false
        tableScroll.setContentHuggingPriority(.defaultLow, for: .vertical)

        // Detail: buttons row + read-only license/description text.
        websiteButton.title = String(localized: "Website")
        websiteButton.bezelStyle = .rounded
        websiteButton.target = self
        websiteButton.action = #selector(openWebsite)
        repoButton.title = String(localized: "Repository")
        repoButton.bezelStyle = .rounded
        repoButton.target = self
        repoButton.action = #selector(openRepository)
        let buttonRow = NSStackView(views: [websiteButton, repoButton, NSView()])
        buttonRow.orientation = .horizontal
        buttonRow.spacing = 8

        detail.isEditable = false
        detail.isSelectable = true
        detail.drawsBackground = true
        detail.font = NSFont.monospacedSystemFont(ofSize: 11, weight: .regular)
        detail.textContainerInset = NSSize(width: 6, height: 6)
        detail.isVerticallyResizable = true
        detail.isHorizontallyResizable = false
        detail.autoresizingMask = [.width]
        detail.textContainer?.widthTracksTextView = true
        let detailScroll = NSScrollView()
        detailScroll.documentView = detail
        detailScroll.hasVerticalScroller = true
        detailScroll.borderType = .bezelBorder
        detailScroll.translatesAutoresizingMaskIntoConstraints = false

        let ack = NSTextField(wrappingLabelWithString: notices.acknowledgement + externalToolsLine())
        ack.font = NSFont.systemFont(ofSize: 11)
        ack.textColor = .secondaryLabelColor

        // Explicit constraints (an NSStackView split the two scroll views
        // unpredictably): search on top, table a fixed fraction, detail fills the
        // rest, acknowledgement pinned to the bottom.
        let pad: CGFloat = 12
        for v in [search, buttonRow, tableScroll, detailScroll, ack] {
            v.translatesAutoresizingMaskIntoConstraints = false
            content.addSubview(v)
        }
        func pin(_ v: NSView, top: NSLayoutYAxisAnchor, gap: CGFloat) -> [NSLayoutConstraint] {
            [v.topAnchor.constraint(equalTo: top, constant: gap),
             v.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: pad),
             v.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -pad)]
        }
        NSLayoutConstraint.activate(
            pin(search, top: content.topAnchor, gap: pad)
            + pin(tableScroll, top: search.bottomAnchor, gap: 8)
            + pin(buttonRow, top: tableScroll.bottomAnchor, gap: 8)
            + pin(detailScroll, top: buttonRow.bottomAnchor, gap: 8)
            + pin(ack, top: detailScroll.bottomAnchor, gap: 8)
            + [tableScroll.heightAnchor.constraint(equalTo: content.heightAnchor, multiplier: 0.4),
               ack.bottomAnchor.constraint(equalTo: content.bottomAnchor, constant: -pad)])
    }

    private func externalToolsLine() -> String {
        guard !notices.externalTools.isEmpty else { return "" }
        let names = notices.externalTools.map(\.name).joined(separator: ", ")
        return "\n\n" + String(format: String(localized: "External tools (invoked, not bundled): %@"), names)
    }

    // MARK: - Filtering + selection

    @objc private func filterChanged() {
        let q = search.stringValue.trimmingCharacters(in: .whitespaces).lowercased()
        filtered = q.isEmpty ? notices.components : notices.components.filter {
            $0.name.lowercased().contains(q) || $0.license.lowercased().contains(q)
                || $0.description.lowercased().contains(q)
        }
        table.reloadData()
        if let first = filtered.first {
            table.selectRowIndexes([0], byExtendingSelection: false)
            showDetail(first)
        } else {
            detail.string = ""
            websiteButton.isEnabled = false; repoButton.isEnabled = false
        }
    }

    private var selectedComponent: ThirdPartyComponent? {
        filtered.indices.contains(table.selectedRow) ? filtered[table.selectedRow] : nil
    }

    private func showDetail(_ c: ThirdPartyComponent) {
        websiteButton.isEnabled = !c.website.isEmpty
        repoButton.isEnabled = !c.repository.isEmpty
        var text = "\(c.name)  \(c.version)\n\(c.license)\n\(c.copyright)\n"
        if !c.note.isEmpty { text += "\(c.note)\n" }
        text += "\n\(c.description)\n"
        text += "\n" + String(repeating: "─", count: 60) + "\n\n"
        text += licenseText(c.licenseFile)
        detail.string = text
        detail.scrollToBeginningOfDocument(nil)
    }

    private func licenseText(_ file: String) -> String {
        let base = (file as NSString).deletingPathExtension
        let ext = (file as NSString).pathExtension
        guard let url = Bundle.main.url(forResource: base, withExtension: ext, subdirectory: "Licenses")
                ?? Bundle.main.url(forResource: base, withExtension: ext),
              let data = try? Data(contentsOf: url) else {
            return String(localized: "License text not found.")
        }
        return String(decoding: data, as: UTF8.self)
    }

    @objc private func openWebsite() {
        if let c = selectedComponent, let url = URL(string: c.website) { NSWorkspace.shared.open(url) }
    }
    @objc private func openRepository() {
        if let c = selectedComponent, let url = URL(string: c.repository) { NSWorkspace.shared.open(url) }
    }

    // MARK: - NSTableView

    func numberOfRows(in tableView: NSTableView) -> Int { filtered.count }

    func tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?, row: Int) -> NSView? {
        guard let colID = tableColumn?.identifier.rawValue, filtered.indices.contains(row) else { return nil }
        let c = filtered[row]
        let id = NSUserInterfaceItemIdentifier("cell")
        let field = (tableView.makeView(withIdentifier: id, owner: self) as? NSTextField) ?? {
            let f = NSTextField(labelWithString: ""); f.identifier = id
            f.usesSingleLineMode = true; f.lineBreakMode = .byTruncatingTail
            f.font = NSFont.systemFont(ofSize: 12); return f
        }()
        switch colID {
        case "name": field.stringValue = c.name; field.textColor = .labelColor
        case "version": field.stringValue = c.version; field.textColor = .secondaryLabelColor
        case "license": field.stringValue = c.license; field.textColor = .secondaryLabelColor
        default: field.stringValue = c.website; field.textColor = .secondaryLabelColor
        }
        return field
    }

    func tableViewSelectionDidChange(_ notification: Notification) {
        if let c = selectedComponent { showDetail(c) }
    }
}
